//COMPILE MODULES
rad.includes.modules([
	"keycode",
	"array",
	"object",
	"math",
	"vector",
	"dom",
	"mouse",
	"element",
	"ui",
	"drag",
	"panels",
	"localstorage"
]);
//COMPILE SOURCES
rad.includes.source([
	"draft/src/draft.js",
	"draft/src/drawing.js",
	"draft/src/io.js",
	"draft/src/script.js",
	"draft/src/node_parameters.js",
	"draft/src/node.js",
	"draft/src/port.js",
	"draft/src/line.js",
	"draft/src/node_framework.js",
	"draft/src/node_browser.js",
	"draft/nodes/include_nodes.js",
	"draft/src/submenu.js",
	"draft/src/renderer.js",
	"draft/src/marquee.js"
]);